Fix ibc transfer and update scripts
mars-protocol/red-bank pull request #175
Opened 2023-02-03 15:28 UTC by piobab

2023-02-03 15:55 UTC, larry0x approved these changes

2023-02-03 15:57 UTC, larry0x commented
For context, `timeout_height` should be the block height of the receiver chain, not the sender chain. It's not possible to know the latest Mars Hub block height from inside our Osmosis contract, so here we only specify the `timeout_timestamp`, while leaving the `timeout_height` empty.

2023-02-03 17:01 UTC, grod220 approved these changes
Is there a way to write tests for this?

2023-02-03 18:20 UTC, brimigs commented on scripts/deploy/osmosis/config.ts
> +const mars = 'ibc/ACA4C8A815A053CC027DB90D15915ADA31939FA331CE745862CDD00A2904FA17'
mars testnet & mainnet denoms are different. Mars mainnet denom will be announced in 4 hours once IBC is enabled.

2023-02-03 18:20 UTC, brimigs commented on scripts/deploy/osmosis/config.ts
> +  channelId: 'channel-2083',
this is the testnet channel. I believe its going to be channel-1? We will know in a couple hours

2023-02-03 18:20 UTC, brimigs commented on scripts/deploy/osmosis/config.ts
> -export const osmoOracle: OracleConfig = {
Was Bob able to test his fix for this?

2023-02-04 20:50 UTC, piobab commented on scripts/deploy/osmosis/config.ts
> +  channelId: 'channel-2083',
Mars -> Osmosis: channel-1
Osmosis -> Mars: channel-557

2023-02-04 20:50 UTC, piobab commented on scripts/deploy/osmosis/config.ts
> -export const osmoOracle: OracleConfig = {
Yes, he confirmed me. I removed it on testnet on Friday.

2023-02-04 20:50 UTC, piobab commented on scripts/deploy/osmosis/config.ts
> +const mars = 'ibc/ACA4C8A815A053CC027DB90D15915ADA31939FA331CE745862CDD00A2904FA17'
Updated

2023-02-04 20:51 UTC, piobab commented
I updated config to use correct mainnet params.

2023-02-05 14:29 UTC, dancreee requested changes

2023-02-05 14:29 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
>    base_asset_symbol: 'OSMO',
osmo1jklpvl3446z5qw58cvq8hqvthzjtsfvs9j65tq for mainnet should also be: osmo14w4x949nwcrqgfe53pxs3k7x53p0gvlrq34l5n

2023-02-05 14:30 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
>    base_asset_symbol: 'OSMO',
(multisigAddr that is)

2023-02-05 14:34 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
>    base_asset_symbol: 'OSMO',
updated in https://github.com/mars-protocol/red-bank/pull/175/commits/2d8c5f110004399707cb0d00080f680c3033cc6c

2023-02-05 14:35 UTC, dancreee approved these changes

2023-02-06 10:49 UTC, dancreee approved these changes

2023-02-06 15:53 UTC, merged