[WIP] Update deployment config
mars-protocol/red-bank pull request #264
Opened 2023-07-19 17:19 UTC by pacmanifold

2023-07-27 14:11 UTC, piobab commented on scripts/deploy/neutron/config_mainnet.ts
> +  swapRoutes: [atomNtrnRoute, atomUsdcRoute, ntrnUsdcRoute, atomMarsRoute],
@markonmars could you please double check the routes?

2023-07-27 18:08 UTC, dancreee approved these changes

2023-07-27 18:09 UTC, dancreee requested changes
see comments on TWAP price sources should be normalised to USD

2023-07-27 18:10 UTC, dancreee commented on scripts/deploy/neutron/config_mainnet.ts
> +  price_source: {
Do we need MARS in the oracle as a price source I mean*

2023-07-27 18:59 UTC, dancreee commented on scripts/deploy/neutron/config_mainnet.ts
> +    astroport_twap: {
here is the NTRN/ATOM pair: https://www.mintscan.io/neutron/wasm/contract/neutron1e22zh5p8meddxjclevuhjmfj69jxfsa8uu3jvht72rv9d8lkhves6t8veq

2023-07-27 20:57 UTC, piobab commented on scripts/deploy/neutron/config_mainnet.ts
> +    astroport_twap: {
Changed to Ntrn <-> Atom pool.
If second asset (in that case atom != uusd) we take price source for the atom and multiply by first one. See https://github.com/mars-protocol/red-bank/blob/master/contracts/oracle/wasm/src/helpers.rs#L163

2023-07-27 20:57 UTC, piobab commented on scripts/deploy/neutron/config_mainnet.ts
> +  price_source: {
Confirmed with Tim. Removed.

2023-07-27 20:57 UTC, piobab commented on scripts/deploy/neutron/config_mainnet.ts
> +  reserve_factor: '0.1',
Changed to 0.1 for all assets. Confirmed with Jon.

2023-07-28 16:42 UTC, dancreee approved these changes

2023-07-30 14:30 UTC, dancreee requested changes

2023-07-30 14:30 UTC, dancreee commented on scripts/deploy/neutron/config_mainnet.ts
> +  denom: axlUsdcDenom,
I think this denom should be 'usd' not 'ibc/F082B65C88E4B6D5EF1DB243CDA1D331D002759E938A0F5CD3FFDC5D53B3E349'?

2023-07-30 14:39 UTC, dancreee requested changes

2023-07-30 14:39 UTC, dancreee commented on scripts/deploy/neutron/config_mainnet.ts
> +export const atomNtrnRoute = {
not sure why we need an atom -> ntrn route? should only need atom -> usdc.axl + atom -> mars?

2023-07-30 14:39 UTC, dancreee commented on scripts/deploy/neutron/config_mainnet.ts
> +export const ntrnUsdcRoute = {
we seem to be missing

1. ntrn -> mars route
2. usdc.axl -> mars route

Essentially for every market asset we need a route to both usdc.axl and mars - the only asset we don't need usdc.axl route for is usdc.axl asset itself (but that asset still needs a mars route)

2023-07-30 14:49 UTC, dancreee commented
@markonmars could you assist in reviewing the swap routes for rewards collector please?

2023-07-31 02:02 UTC, markonmars commented on scripts/deploy/neutron/config_mainnet.ts
We need to have some additional routes for us to be able to liquidate properly. 

Current status of what IMO are required routes based on this config : 

- [x] atom -> mars
- [ ] atom -> ntrn
- [x] atom -> usdc

- [x] ntrn -> mars
- [ ] ntrn -> atom
- [x] ntrn -> usdc

- [ ] usdc -> atom
- [x] usdc -> mars
- [ ] usdc -> ntrn

2023-07-31 11:24 UTC, markonmars commented on scripts/deploy/neutron/config_mainnet.ts
You're right it does, so we will need those as well.

2023-07-31 12:19 UTC, markonmars commented on scripts/deploy/neutron/config_mainnet.ts
> +  swapRoutes: [atomNtrnRoute, atomUsdcRoute, ntrnUsdcRoute, atomMarsRoute],
added my thoughts [here](https://github.com/mars-protocol/red-bank/pull/264#discussion_r1278688621)

2023-07-31 12:21 UTC, markonmars commented on scripts/deploy/neutron/config_mainnet.ts
> +  swapRoutes: [atomNtrnRoute, atomUsdcRoute, ntrnUsdcRoute, atomMarsRoute],
LGTM

2023-07-31 15:12 UTC, piobab commented
Updated testnet addresses to the one on neutron testnet.

2023-07-31 15:22 UTC, piobab approved these changes

2023-07-31 15:25 UTC, piobab commented
Before merge to master all commits should be squashed into one.

2023-08-01 13:05 UTC, markonmars approved these changes

2023-08-01 20:07 UTC, piobab commented
Squashed to single commit. Diff between old https://github.com/mars-protocol/red-bank/tree/feat/update-deployment-config-copy and current one is empty so should be good.

2023-08-01 20:49 UTC, merged