Fix: Use `NeutronMsg::IbcTransfer` for neutron reward collector
mars-protocol/red-bank pull request #269
Opened 2023-07-21 18:27 UTC by pacmanifold

2023-07-21 20:07 UTC, apollo-sturdy commented on .vscode/settings.json
> +        "./contracts/rewards-collector/base/Cargo.toml"
Should this file be pushed?

2023-07-21 20:14 UTC, apollo-sturdy commented on contracts/rewards-collector/base/Cargo.toml
> +neutron-sdk         = { workspace = true }
Should this not only be in `rewards-collector-neutron`?

2023-07-21 20:26 UTC, apollo-sturdy commented on contracts/rewards-collector/base/src/contract.rs
> +            timeout: IbcTimeout::with_timestamp(env.block.time.plus_seconds(cfg.timeout_seconds)),
Personally think default implementations in traits can be a bit confusing (hard to tell which implementation is being used). Perhaps leave it unimplemented and implement the trait for OsmosisCollector?

2023-07-21 20:32 UTC, apollo-sturdy approved these changes
Looks good. See comments for questions and suggestions

2023-07-22 14:54 UTC, dancreee approved these changes

2023-07-23 10:36 UTC, piobab requested changes

2023-07-23 10:36 UTC, piobab commented on contracts/rewards-collector/neutron/src/lib.rs
> +pub mod entry {
I don't like that we duplicate all msgs execution in neutron / osmosis impl. IMO it can be done the way we do in Oracle etc where we can impl Trait for specific chain impl.

2023-07-23 10:36 UTC, piobab commented on contracts/rewards-collector/neutron/src/lib.rs
> +                recv_fee: vec![coin(0u128, "untrn")],
Hmmm 0? Does it work?

2023-07-23 10:36 UTC, piobab commented on contracts/rewards-collector/base/src/contract.rs
> +            timeout: IbcTimeout::with_timestamp(env.block.time.plus_seconds(cfg.timeout_seconds)),
I agree.

2023-07-23 22:28 UTC, pacmanifold commented on .vscode/settings.json
> +        "./contracts/rewards-collector/base/Cargo.toml"
no

2023-07-23 22:36 UTC, pacmanifold commented on contracts/rewards-collector/neutron/src/lib.rs
> +                recv_fee: vec![coin(0u128, "untrn")],
not sure. have not managed to test against testnet yet. but according to doc comment in the `IbcFee` it only exists for compatibility with ICS-29 and must be set to zero. https://github.com/neutron-org/neutron-sdk/blob/16be78cd19d4a209f37cceead67da8547a2a19af/packages/neutron-sdk/src/bindings/msg.rs#L20-L22

2023-07-24 09:39 UTC, piobab commented on packages/types/src/rewards_collector.rs
> +    pub neutron_ibc_config: Option<NeutronIbcConfig>,
It is not ideal that we add neutron specific config to common instantiate but for now we can leave it as it is. This is a candidate for improvement.

2023-07-24 09:43 UTC, piobab commented
Tests are only for Osmosis but they cover most of the logic. Ideally we move common test to `rewards-collector/test` directory and chain specific to `rewards-collector-osmosis/tests and rewards-collector-neutron/tests` but I suppose this requires more time to do it.

2023-07-24 12:18 UTC, grod220 commented
Besides Piotr's comments, I didn't find anything additional. Good job!

2023-07-26 15:03 UTC, piobab approved these changes

2023-07-26 20:11 UTC, piobab commented
Squashed 10 commits to one clean msg.

2023-07-26 20:29 UTC, merged